# Generated by Django 4.2.5 on 2023-09-11 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Introduction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('intro', models.CharField(blank=True, max_length=1000)),
                ('video_link', models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
